name: Run eslint on changed files
description: Run ESLint on JavaScript files
author: jackton1
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT'
    required: true
    default: ${{ github.token }}
  ref:
    description: 'The target branch of the pull request or the current branch to run on changes since the first commit.'
    required: true
    default: ${{ github.base_ref }}
  config_path:
    description: Eslint configuration path
    required: false
    default: '.eslintrc'
  ignore_path:
    description: Eslint ignore path
    required: false
    default: ''
  extensions:
    description: Comma separated list of extensions
    required: false
    default: 'ts,tsx,js,jsx'
  extra_args:
    description: Eslint extra arguments
    required: false
    default: ''
  exclude_path:
    description: String or list of files to exclude entirely
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: check-square
  color: white
