name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.5

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.5
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn
        working-directory: test-app

      - name: Run ESLint on changed files
        uses: ./
        with:
          config-path: "test-app/package.json"
          extensions: "ts,tsx"
          extra-args: "--max-warnings=0"
